[package]
name = "imgui-wgpu"
version = "0.1.0"
authors = ["Steven Wittens <steven@acko.net>"]
edition = "2018"

[features]
default = []
metal = ["wgpu/metal"]
dx11 = ["wgpu/dx11"]
dx12 = ["wgpu/dx12"]
vulkan = ["wgpu/vulkan"]

[dependencies]
wgpu = { git = "https://github.com/gfx-rs/wgpu-rs.git" }
cgmath = "0.17"
env_logger = "0.5"
glsl-to-spirv = "0.1"
log = "0.4"
num-traits = "0.2.6"
imgui = "0.0.23"
imgui-winit-support = "0.0.23"

[dev-dependencies]
# winit = "*"
